language: node_js
node_js:
    - '16'
    - '14'
    - 'stable'

sudo: false

matrix:
    fast_finish: true
    include:
        - node_js: 'node'
          env: LINT=true

services:
    - docker

before_script:
    - npm run start-services
    - npm run lint
    - sleep 3

after_script:
    - npm run coverage
    - npm run check-coverage
    - npm run update-coveralls

notifications:
    email:
        on_success: never
        on_failure: change
